### ISSUE TITLE
deploy automatically

### ISSUE THREAD

**Issue by ignatandrei** [cristeaibogdan/hephaestus-web#8]
In the action that deployes to github pages add 404.html being index.html
( hint: github actions runs on a pc . In that case, the OS is ubuntu - linux. See cp )

**Comment by ignatandrei** [comment]
Add a .nokeyll file

**Comment by cristeaibogdan** [comment]
404.html => is now handled exclusively in the github action. No other input is necessary.
.nojekyll file => already done under peaceiris/actions-gh-pages@v4. More info: https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-enable-built-in-jekyll-enable_jekyll
